// features-data.js
export const featuresData = [
  {
    id: 1,
    name: "Custom Domain",
    icon: "Globe",
    raivcoo: { status: "No", highlight: true },
    behance: { status: "No", highlight: false },
    carrd: { status: "Paid", highlight: false },
    framer: { status: "Paid", highlight: false },
    webflow: { status: "Paid", highlight: false },
  },

  {
    id: 2,
    name: "Image Optimization",
    icon: "Image",
    raivcoo: { status: "Free", highlight: true },
    behance: { status: "Limited", highlight: false },
    carrd: { status: "Free", highlight: false },
    framer: { status: "Free", highlight: false },
    webflow: { status: "Free", highlight: false },
  },
  {
    id: 3,
    name: "Password Protection",
    icon: "Lock",
    raivcoo: { status: "Free", highlight: true },
    behance: { status: "No", highlight: false },
    carrd: { status: "Paid", highlight: false },
    framer: { status: "Free", highlight: false },
    webflow: { status: "Paid", highlight: false },
  },
  {
    id: 4,
    name: "Custom OG Image",
    icon: "Image",
    raivcoo: { status: "Free", highlight: true },
    behance: { status: "No", highlight: false },
    carrd: { status: "No", highlight: false },
    framer: { status: "Free", highlight: false },
    webflow: { status: "Free", highlight: false },
  },
  {
    id: 5,
    name: "Favicon Support",
    icon: "Star",
    raivcoo: { status: "Free", highlight: true },
    behance: { status: "No", highlight: false },
    carrd: { status: "Free", highlight: false },
    framer: { status: "Free", highlight: false },
    webflow: { status: "Free", highlight: false },
  },
  {
    id: 6,
    name: "Customizable Layout",
    icon: "Layout",
    raivcoo: { status: "Free", highlight: true },
    behance: { status: "No", highlight: false },
    carrd: { status: "Free", highlight: false },
    framer: { status: "Free", highlight: false },
    webflow: { status: "Free", highlight: false },
  },
  {
    id: 7,
    name: "Hide/Show Sections Dynamically",
    icon: "Eye",
    raivcoo: { status: "Free", highlight: true },
    behance: { status: "No", highlight: false },
    carrd: { status: "No", highlight: false },
    framer: { status: "Custom", highlight: false },
    webflow: { status: "Custom", highlight: false },
  },
  {
    id: 8,
    name: "Analytics",
    icon: "BarChart",
    raivcoo: { status: "Free", highlight: true },
    behance: { status: "Limited", highlight: false },
    carrd: { status: "No", highlight: false },
    framer: { status: "Paid", highlight: false },
    webflow: { status: "Paid", highlight: false },
  },
  {
    id: 9,
    name: "Multi host Videos website Embedding",
    icon: "Video",
    raivcoo: { status: "Free", highlight: true },
    behance: { status: "Limited", highlight: false },
    carrd: { status: "Limited", highlight: false },
    framer: { status: "Free", highlight: false },
    webflow: { status: "Free", highlight: false },
  },

  {
    id: 10,
    name: "Social Media Integration",
    icon: "Share2",
    raivcoo: { status: "Free", highlight: true },
    behance: { status: "Free", highlight: false },
    carrd: { status: "Free", highlight: false },
    framer: { status: "Free", highlight: false },
    webflow: { status: "Free", highlight: false },
  },
];

export const platforms = [
  { id: "raivcoo", name: "Raivcoo", isPrimary: true },
  { id: "behance", name: "Behance", isPrimary: false },
  { id: "carrd", name: "Carrd.co", isPrimary: false },
  { id: "framer", name: "Framer", isPrimary: false },
  { id: "webflow", name: "Webflow", isPrimary: false },
];
